name: Build and Push Multi-Arch Docker Image

on:
  workflow_dispatch:
  registry_package:
    types: [published, updated]

env:
  REGISTRY: ghcr.io
  USERNAME: ${{ github.actor }}
  PASSWORD: ${{ secrets.GITHUB_TOKEN }}
  IMAGE_NAME: ${{ github.repository }}

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    if: ${{ github.event.registry_package.package_version.container_metadata.tag.name == 'dev' || github.event_name == 'workflow_dispatch' }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ env.USERNAME }}
          password: ${{ env.PASSWORD }}

      - name: Create Dockerfile dynamically
        run: |
          cat <<EOF > .github/workflows/dev.dockerfile
          ARG REGISTRY
          ARG IMAGE_NAME
          FROM \${REGISTRY}/\${IMAGE_NAME}:dev
          EOF

      - name: Build and push Docker image
        uses: docker/build-push-action@v6
        with:
          context: .
          push: true
          tags: |
            ${{env.REGISTRY}}/${{env.IMAGE_NAME}}:dev-multi-arch
          platforms: linux/amd64,linux/arm64
          build-args: |
            REGISTRY=${{env.REGISTRY}}
            IMAGE_NAME=${{env.IMAGE_NAME}}
          file: .github/workflows/dev.dockerfile
