name: Build and Push Multi-Platform Devcontainer

on:
  workflow_dispatch:
  pull_request:
  push:
    branches:
      - main
      - master

env:
  REGISTRY: ghcr.io
  USERNAME: ${{ github.actor }}
  PASSWORD: ${{ secrets.GITHUB_TOKEN }}
  IMAGE_NAME: ${{ github.repository }}

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    permissions:
      packages: write
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ env.USERNAME }}
          password: ${{ env.PASSWORD }}

      - name: Build and push multi-platform devcontainer
        # uses: devcontainers/ci@v0.3
        # with:
        #   imageName: ${{env.REGISTRY}}/${{env.IMAGE_NAME}}
        #   cacheFrom: ${{env.REGISTRY}}/${{env.IMAGE_NAME}}
        #   imageTag: dev
        #   configFile: .devcontainer/devcontainer.json
        #   platform: linux/amd64,linux/arm64
        #   push: always
        #   runCmd: echo "Hello World"
        run: |
           npm install -g @devcontainers/cli
           devcontainer build \
            --workspace-folder . \
            --config .devcontainer/prebuild-devcontainer.json \
            --push true \
            --image-name ${{env.REGISTRY}}/${{env.IMAGE_NAME}}:dev \
            --platform linux/amd64,linux/arm64
